### ISSUE TITLE
Ticwatch pro 3 (GPS)

### ISSUE THREAD

**Issue by JackRichardson666** [fmeum/WearAuthn#19]
**What went wrong?**
The application does not work on the watch, after installation it works like on a phone and asks to install it

**Steps to reproduce**
1. Installed the application via adb

**Which model is your watch?**
WF12106

**Which Android version is running on your watch?**
2.17(WearOS)

**Which version of WearAuthn are you using?**
0.9.17

**Screenshots**
![uJJzbJqa8Ls](https://user-images.githubusercontent.com/64367044/211084870-4c392ccb-0288-41bd-983d-5e7a93134fa4.jpg)

**Comment by fmeum** [comment]
The two apps come as separate APKs/AABs. If you have the one for the phone on your watch, then it's the wrong file. Can you install it from the Play Store on your watch instead?

**Comment by JackRichardson666** [comment]
> The two apps come as separate APKs/AABs. If you have the one for the phone on your watch, then it's the wrong file. Can you install it from the Play Store on your watch instead?

no, for some reason I can't update/download apps from Google play
