### ISSUE TITLE
Watch detected as microphone on Windows 11 Notebook

### ISSUE THREAD

**Issue by archef2000** [fmeum/WearAuthn#21]
**What went wrong?**
Watch detected as microphone on Windows 11 Notebook after single-factor mode enabled in WearAuthn

**Steps to reproduce**
1. Connect watch to notebook
2. Setup WebAuthn on websites
3. Enable single-factor mode in WearAuthn
4. Reconnect to notebook
5. Model is displayed correctly but not recognised as WebAuthn key

**Which model is your watch?**
Galaxy Watch 5 Pro (SM-R925F)

**Which Android version is running on your watch?**
Android: 11
Wear OS: 3.5
One UI: 4.5

**Which version of WearAuthn are you using?**
0.9.17

**Screenshots**
![Screenshot 2023-06-05 110510](https://github.com/fmeum/WearAuthn/assets/69057532/559144c9-01be-457b-a3e3-fcb1e8871bc8)

**What i have done**
1. Remove watch from bluetooth list
2. Reboot both devices
3. Reinstall Watch app

**Comment by fmeum** [comment]
There isn't anything in particular that changes about the Bluetooth level behavior of WearAuthn when single-factor mode is enabled.

I think that this is an instance of a more general issue that is unfortunately inherent in the design: Most Bluetooth stacks don't handle devices well that dynamically change their Bluetooth identity (e.g. between sound/keyboard/mouse). I have had similar issues in the past, especially with Windows hosts, that required multiple resets of both parts of the connection to resolve.

**Comment by archef2000** [comment]
I reset my Watch and it now works again even when it is displyed as an microphone.
